### ISSUE TITLE
Use of Conditional Debug Attribute?

### ISSUE THREAD

**Issue by pha3z** [safakgur/guard#16]
First off, let me say my personal experience has *not* been your typical enterprise-grade business software applications.  So my perspective here may be a skewed.  Moving on...

With the kinds of applications I usually work on, 99% of conditional bugs are going to be found during debug testing and will rarely ever occur in a production build. I was considering writing my own fluent conditions library that used conditional debug attributes so that the methods are completely omitted in the release build.  The really cool thing about this is that I could use tests anywhere I want in code without worrying about final performance.

I found Guard and I'm very impressed with the thoroughness of design decisions. So I was wondering what is your opinion about using fluent conditions with conditional debug attributes? Do you feel it would be warranted to add such a feature to Guard?  If not conditional debug, it could be a custom conditional variable so that the developer can turn on/off compilation of the Guard statements -- simply by declaring the variable at program start.

**Comment by safakgur** [comment]
Hi, this is in fact something I want to include but I'm not sure how.

Thinking of `ConditionalAttribute`:
* It can't be used on classes except attributes, so we can't mark the whole `Guard` class.
* It can't be used on methods with return values, so we can't use it on our fluent assertions.
* It checks whether a symbol is defined - but for Guard it would make more sense to enable runtime validations by default, so what we want to check instead is whether a symbol is _undefined_. AFAIK there is no way to negate like `[Conditional("!SYMBOL")]`.

`#if` directives wouldn't work since they check the symbols in Guard's assembly. But we need to check the symbols in the caller assembly like `ConditionalAttribute` does.

I'll investigate more on this. In the meantime I'm open to suggestions.

Thank you for your interest.

**Comment by pha3z** [comment]
Bummer.  I didn't realize about the limitation of Conditional attributes on void methods only.

I don't see any way to get around this limitation if the intent is to have a fluent syntax. :(

**Comment by pha3z** [comment]
After some introspection, I realized I should be using Assert frequently.  The whole purpose of Assert is to test for conditions specifically in Debug build only.  Trying to use Guard only in Debug builds doesn't really make sense.

**Comment by safakgur** [comment]
Glad to hear! I'm closing the issue for now - feel free to comment to re-open or open a new one.
