### ISSUE TITLE
Excellent!

### ISSUE THREAD

**Issue by JechoJekov** [safakgur/guard#2]
Hi,

Sorry to create an issue but this is the only way to leave a comment on GitHub :-)

This is an excellent library - well designed, nicely implemented and documented and the first one I have seen for fluent validation that actually makes sense from performance point of view :-) I guess C# 7.2 made this possible :-)

Thank you for creating this excellent library!

I have a question though: while the library's version is `alpha` it seems pretty complete and well tested. Is there anything that you consider should be tested or improved before it s used on production?

**Comment by safakgur** [comment]
Hi, it's ok to create an issue for this. :)

The reason why the project is still in alpha is because I couldn't get the chance to complete the unit tests. More than half of the tests you see in the project are actually not implemented.

I'd love to work on this more but I've been really busy for the last couple of months due to my day-time job. So it may take one month or so before I can confidently release 1.0.

I don't think I'll add any new features before I complete the unit tests and release a stable version. You're welcome to add issues for feature requests and bug reports. I'm also open to pull requests providing more test coverage.

Thank you for your interest in the library.
