### ISSUE TITLE
Guard.Argument(x).Equal<T> return type error

### ISSUE THREAD

**Issue by HugoPeters1024** [safakgur/guard#20]
## Expected Behaviour
Guard.Argument(x).Equal{InvalidOperationException}(_not x_) returns an InvalidOperationException

## Actual Behaviour
Guard.Argument(x).Equal{InvalidOperationException}(_not x_) returns an ArgumentException

## Probable Cause
The implementation of Equal{T} is not respecting the type of T and is thus equivalent to the non templated variant.

_Actual code uses tags of course, but markdown does not support them_

**Comment by safakgur** [comment]
Hi, `Equal` guards do not modify the argument - they return the original `ArgumentInfo<T>` by reference. Do you mean it _throws_ an `ArgumentException`?

If this is the case, it is supposed to throw an `ArgumentException` since you are validating an argument. If you're verifying the validity of an operation, use `Guard.Operation` - it throws an `InvalidOperationException` when you pass `false` as its first argument.

If you mean something else, can you provide a [minimal, complete and verifiable example][1] of your code? You can use [code blocks][2] to post a simple Main method.

[1]: https://stackoverflow.com/help/mcve
[2]: https://help.github.com/articles/creating-and-highlighting-code-blocks

**Comment by safakgur** [comment]
I'm closing this as by-design. Feel free to reopen if you think there is a misunderstanding.
