### ISSUE TITLE
Add NotWhiteSpace overload that takes a string for the error message

### ISSUE THREAD

**Issue by rmcc13** [safakgur/guard#29]
**Is your feature request related to a problem?**
A description of the problem. Ex. I'm always frustrated when [...]

Unlike the `.NotEmpty` string guard, `.NotWhiteSpace` does not have an overload that takes a string argument for the error message. The only implementation of `.NotWhiteSpace` requires a `Func<string, string>` argument for providing an error message.

**Describe the solution you'd like**
A description of what you want to happen.

Add an overload of the `NotWhiteSpace` string guard: `NotWhiteSpace(in this ArgumentInfo<string> argument, string message)`

**Comment by safakgur** [comment]
The reason why `NotEmpty` accepts a string is because the only possible value the argument can have when this precondition fails is `string.Empty`. `NotWhiteSpace` on the other hand can be caused by a lot of different string values.

With that said, I agree that in the majority of cases the actual value is irrelevant. Therefore I'm adding this overload right now.

Thank you for the request.

**Comment by rmcc13** [comment]
That's interesting, I didn't think about it that way. Yea I have some cases where I don't care about the value and just want to provide a generic error message. Thanks for addressing that so quickly
