### ISSUE TITLE
Unique values in the collection

### ISSUE THREAD

**Issue by snekbaev** [safakgur/guard#32]
Hi,

curious if checking the uniqueness of values (with optional comparer parameter) should be a core functionality. Say, I have an array of ints: `1,1,2` and exception is thrown because values are not unique. I'm trying to replace custom validation with the guard library.

Thank you!

**Comment by safakgur** [comment]
Hi, adding a collection guard for this makes sense since this really is a very common validation.

I'll try to add a `DoesNotContainDuplicate` guard this week. You can [extend](https://github.com/safakgur/guard/blob/dev/docs/extensibility.md) Guard yourself if you don't want to wait. And feel free to open a PR if you do.

Thank you for the suggestion.

**Comment by snekbaev** [comment]
I can absolutely wait and thank you as always :)

**Comment by safakgur** [comment]
Implemented in [1.10.0][1], thanks again for the suggestion.

[1]: https://github.com/safakgur/guard/releases/tag/v1.10.0
