### ISSUE TITLE
Another Performance Related Issue

### ISSUE THREAD

**Issue by AlexVPerl** [safakgur/guard#39]
First of, thank you for creating this wonderful library. I've been on a search for a Guard library evaluating a number of them on Nuget and have to say that yours is very comprehensive and is the most syntax friendly in my opinion. Good job!

My suggestion is about performance when it comes to member expressions. Ability to take in member expressions is what makes this library very syntax friendly and attractive to use. 

I see that you compile expressions, which is obviously very expensive and you are very explicit about this in the documentation. I've also read issue #13 where this is discussed. 

So my suggestion would be to utilize constant expressions instead. It would involve unwrapping the whole expression tree. Its a fair bit more work, but also a lot better performance, about 40-50x faster from what I've tested.

**Comment by safakgur** [comment]
Hi Alex,

Yes, member expressions are used to get the argument names and compilation is necessary to get the values. Both initializing an expression and compiling it are expensive actually but you are right that the compilation being the bigger issue.

For initializing guarded arguments (`Guard.Argument` overloads): I don't understand how I can use constant expressions for this as I don't know a way to get the value from a member expression without compiling it. Can you give me an example or point me to a resource or code where this is used? I'd love to implement this if it is possible.

For member guards: Compilation costs are fine here because I actually cache the compiled delegates, so the cost is one time only. The creation of the expression itself remains an issue since unfortunately, [those lambdas are not cached][1].

Thank you for using the library, I'm glad you liked it.

[1]: https://stackoverflow.com/q/52793106/704144

**Comment by safakgur** [comment]
Closing this issue as it has been inactive for 43 days. Feel free to re-open if needed.
