### ISSUE TITLE
[Question] Change Exception Types 

### ISSUE THREAD

**Issue by andreas-soroko** [safakgur/guard#41]
Hi and thanks for the great lib! 

[Exception Types](https://github.com/safakgur/guard/blob/dev/docs/design-decisions.md#exception-types)

> Throwing custom exceptions from standard validations seems counter-intuitive and right now, the only way to do so is to use the generic Require<TException> validation.

do you have any plans on this to change it ? 
we have for our micro-services our own error response ( ApiException ) with some custom types ( Type, Status, Path, AdditionalData ) and we would like to use our own exception instead of ArgumentEx.../InvalidOper... 

we also saw that it is possible to extend it but this does not make any sense because we would have to re implement most of your existing functions just to throw our exception

also the Exception interceptor would not fit ( because we wouldnt be able to add additional  data to the exceptions )

**Comment by safakgur** [comment]
Hi,

Guard is intended for _libraries_ where the norm for handling invalid inputs is to throw exceptions.

```c#
namespace Lib
{
    public sealed class Person
    {
        public Person(string firstName, string lastName)
        {
            FirstName = Guard.Argument(firstName, nameof(firstName))
                .NotNull()
                .NotWhiteSpace();

            LastName = Guard.Argument(lastName, nameof(lastName))
                .NotNull()
                .NotWhiteSpace();
        }

        public string FirstName { get; }

        public string LastName { get; }
    }
}
```

But on most business applications, you'll see request models defined as POCOs with validation attributes on their properties.

```c#
namespace App
{
    public class Person
    {
        [Required]
        public string FirstName { get; set; }

        [Required]
        public string LastName { get; set; }
    }
}
```

There are two primary reasons for that:

1. Most deserializers don't support calling a parameterized constructor. They try to create a new instance of the model type using the parameterless constructor and assign the properties one by one, forcing the model to be mutable.
2. It makes more sense to return _all_ validation errors in a response instead of only the first one, so the client wouldn't need to make multiple requests for each invalid property. Throwing on the first invalid parameter would prevent us from validating the rest, therefore we can only know the validity of parameters up to the first failure.

That's why most business applications use POCOs either with the [Validator][1] class or with a library like [FluentValidation][2]. This makes deserializers happy and allows devs to validate all properties of the request model, providing them a collection of validation results that are easier to log and/or return in a 400 response than a catched exception.

To compare: We can trust any instance of the `Lib.Person` class to be valid because it couldn't have been created if the arguments were invalid. And it can't be made invalid afterwards as it is immutable. Instances of the `App.Person` class on the other hand may have null names. So it's best to think of an `App.Person` as a person _request_ or _candidate_ instead of a person _value_. Adding a suffix to the class name (e.g. to make it `PersonRequest`) or putting it in a namespace like `*.Models` would make its purpose clear.

I wish I could be more helpful but I don't recommend using Guard on non-library code as getting invalid input is not really an _exceptional_ case on most business applications. A more suitable place for Guard would be your domain objects.

Thank you for using -or in this case, considering- Guard! Unfortunately, adding custom exception type support to all argument guards are not planned as the use case it enables is out of Guard's scope. Please let me know if I seem to have misunderstood something.

[1]: https://docs.microsoft.com/dotnet/api/system.componentmodel.dataannotations.validator
[2]: https://fluentvalidation.net/
