### ISSUE TITLE
Support for both  directory and file path validation

### ISSUE THREAD

**Issue by prince272** [safakgur/guard#45]
**Is your feature request related to a problem?**
A description of the problem. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
Support for path validation were Guard.Argument(() => name).NotValidFilePath()

**Comment by safakgur** [comment]
Thank you for the feature request.

String format rules of a path will depend on the filesystem being used.

* Which filesystem do you want Guard to support?
* If multiple, how would you like to allow the user to choose?
* What about relative paths, are they considered valid?
* What about network paths?

Usually, the only way to be certain that you can use a path is actually using the path. So instead of something like this:

```c#
public static void Process(string path)
{
    Guard.Argument(() => path).NotNull().NotValidFilePath();

    using (var file = File.OpenRead(path))
    {
        // ...
    }
}
```

One option is to do something like this:

```c#
public static void Process(string path)
{
    Guard.Argument(() => path).NotNull();

    Stream file;
    try
    {
        file = File.OpenRead(path);
    }
    catch (Exception ex)
    when (ex is PathTooLongException || ex is FileNotFoundException)
    {
        throw new ArgumentException(ex.Message, nameof(path), ex);
    }

    using (file)
    {
        // ...
    }
}
```

Or even just this:

```c#
public static void Process(string path)
{
    Guard.Argument(() => path).NotNull();

    using (var file = File.OpenRead(path) )
    {
        // ...
    }
}
```

Doing this last one causes the IO exception `OpenRead` may throw to go up. And that exception would be more useful to the caller than a generic `ArgumentException` anyway.

**Comment by prince272** [comment]
Oh okay. Guard support 
1. Windows File System
2. ....
3. Yes,  relative paths, are considered valid since it maps to a physical path.
4. I don't know much about network paths but why not since their all considered us paths.
