### ISSUE TITLE
How to return the Exception instead of throwing it

### ISSUE THREAD

**Issue by prince272** [safakgur/guard#46]
Is there a way to return the Exception like Guard.Argument(() => extension).NotNull().NotWhiteSpace().GetException().

**Comment by prince272** [comment]
Take a look at the problem here

```
        public string[] GetFileExtensionsByMediaType(MediaType mediaType)
        {
            return mediaType switch
            {
                MediaType.Document => _mediaSettings.DocumentFileExtensions,
                MediaType.Image => _mediaSettings.ImageFileExtensions,
                _ => throw new ArgumentException($"No file extensions were provided by this media type '{mediaType}'.", nameof(mediaType)),
            };
        }
```
I would like to throw Guard.Opeation but it seems it returns a void

**Comment by safakgur** [comment]
Hi, thank you for using the library.

> Is there a way to return the Exception like Guard.Argument(() => extension).NotNull().NotWhiteSpace().GetException().

Unfortunately not. Failed validations throw by design, e.g. `NotNull()` will throw if the argument is null, thus `NotWhiteSpace()` or `GetException()` will never be executed. Implementing this feature would require `ArgumentInfo` to have yet another flag to specify _return-over-throw_, and an internal collection to store exceptions.

Currently, there is no plan to implement this feature.

> Take a look at the problem here
> 
> ```
>         public string[] GetFileExtensionsByMediaType(MediaType mediaType)
>         {
>             return mediaType switch
>             {
>                 MediaType.Document => _mediaSettings.DocumentFileExtensions,
>                 MediaType.Image => _mediaSettings.ImageFileExtensions,
>                 _ => throw new ArgumentException($"No file extensions were provided by this media type '{mediaType}'.", nameof(mediaType)),
>             };
>         }
> ```
> 
> I would like to throw Guard.Opeation but it seems it returns a void

`Guard.Operation` is for throwing `InvalidOperationException`s. I think an `ArgumentException` would make more sense here. May I suggest `Guard.Argument(() => mediaType).Defined()` at the top, or maybe having a static `IReadOnlyDictionary<MediaType, IEnumerable<string>>` instead of the method?

**Comment by prince272** [comment]
okay. Thanks for your support. **Guard** all the way.
