### ISSUE TITLE
Enhanced String char based guards.

### ISSUE THREAD

**Issue by MizMahem** [safakgur/guard#63]
**Describe the solution you'd like**
In the same fashion that there is currently `Whitespace` and `NotWhitespace` similar Guard methods to check for and against string individual chars "Is" methods (`IsDigits`, `IsLetters`, `IsNumbers`, and so on). That is, checking if a string consists entirely of Letters/Digits/Numbers etc, or not these methods. 

```CSharp
public static ref readonly ArgumentInfo<string> Letters(in this ArgumentInfo<string> argument,
	Func<string?, string>? message = null)
{
	if (!argument.Value?.All(char.IsLetter) ?? false)
	{
		var m = message?.Invoke(argument.Value) ?? Messages.StringIsLetters(argument);
		throw Fail(new ArgumentException(m, argument.Name));
	}

	return ref argument;
}
```

Additionally, while implementing similar `ContainsDigits`, `ContainsLetters`, and their inverse methods could be created.

```CSharp
public static ref readonly ArgumentInfo<string> ContainsLetters(in this ArgumentInfo<string> argument,
	Func<string?, string>? message = null)
{
	if (!argument.Value?.Any(char.IsLetter) ?? false)
	{
		var m = message?.Invoke(argument.Value) ?? Messages.StringContainsLetters(argument);
		throw Fail(new ArgumentException(m, argument.Name));
	}

	return ref argument;
}
```

While this can be accomplished with the Regex methods currently, using these methods with the char methods should be considerably faster.

Alternatively, the IEnumerable methods could be expanded to contain `All`, `NotAll`, `Any`, and `NotAny` methods that take predicates to handles this functionality.

```CSharp
public static ref readonly ArgumentInfo<T> All<T>(in this ArgumentInfo<T> argument,
	Func<T, bool> predicate,
	Func<string?, string>? message = null)
	where T : IEnumerable<T>
{
	if (!argument.Value?.All(predicate) ?? false)
	{
		var m = message?.Invoke(argument.Value?.ToString()) ?? Messages.All(argument);
		throw Fail(new ArgumentException(m, argument.Name));
	}

	return ref argument;
}
```

If either of these sorts of functionality would be accepted, I would be willing to submit a pull with it.

**Comment by safakgur** [comment]
Thanks for the suggestion - I agree the new text validations would be useful!

I think it would be safer to use runes instead of chars, and we could probably have these guards for `Span`/`ReadOnlySpan` and `StringValues` structs as well. With the version 2, our argument type will also be a ref struct, allowing us to validate types like spans. So I think it makes sense to wait for v2's release before implementing this feature.

I see value in having text-specific guards as this way the user won't have to write their own letter/digit/etc checks, so let's consider `All`/`NotAll`/`Any`/`NotAny` separate - we can create a new issue for them as generic collection helpers if you'd like.

**Comment by safakgur** [comment]
Hi @MizMahem, I'm retiring Guard - I apologise for any inconvenience, and thank you for all the support. The readme has details.
